# sets maximal velocity and acceleration values along the trajectory
dynamic_params: {
  max_v: 5.0,
  max_a: 5.0
}

waypoints: {
  # your waypoints here. Think about how to best add any number of waypoints
  # and the according velocity and acceleration constraints.
  #x: [0,  5,  10,  15,  20,  25,  30,  30,  25,  20,  15,  10,  5,  0,  0,  5,  10,  15,  20,  25,  30],
  #y: [0,  0,  0,   0,   0,   0,   0,   5,   5,   5,   5,   5,   5,  5,  10, 10, 10,  10,  10,  10,  10],
  #z: [7.5,7.5,7.5, 7.5, 7.5, 7.5, 7.5, 7.5, 7.5, 7.5, 7.5, 7.5, 7.5, 7.5, 7.5, 7.5, 7.5, 7.5, 7.5, 7.5, 7.5],
  x: [0,  5],
  y: [0,  0],
  z: [2,  3],
  
}


